from tkinter import *
root  = Tk()
button_one = Button(root, text="Click me!")
button_two = Button(root, text="Button under work!", state=DISABLED) #By writing state=DISABLED, the button becomes non-functional. We can't even click that button.
button_three = Button(root, text="Padded button!", padx=60, pady=90) #We can control the width and height of the button widget by specifying the coordinate values.
def putlabel():
    l_one = Label(root, text="This label is generated by a mouse click!")
    l_one.pack()
button_four = Button(root, text="Click me to put a label onto the window!", padx=60, pady=60, command=putlabel) #Upon mouse click an action will be performed. That's why we specify which command to perform. In this case we are creating a function which puts a label onto the main window. Upon mouse click, this phenoenon will occur as the function will be called.
button_one.pack()
button_two.pack()
button_three.pack()
button_four.pack()
root.mainloop()